name: Publish EBH to Docker Hub

on:
  push:
    tags:
      - '*'

jobs:
  publish_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and publish image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: thunderysteak/everyhourbot:latest

      